### ISSUE TITLE
Registration validation: Incorrect padding

### ISSUE THREAD

**Issue by micheljung** [FAForever/api#155]
```
[2017-03-25 18:55:53,723] ERROR in app: Exception on /users/validate_registration/Z0FBQUFBQlkxcnc2RFVmV2VMUEpNaWhTSV9oZGEwaFFWQU5CcDFBak9wbU5vV0dNZ095RXhUYVpXT3lfOHpSaEJtMTlyT3pXdWZ1OEc3VDV5a1JwcUhpM1VIcjBZLTFuRW1vUkVKSXdvYU1YSTNBa2V6bmdWSng1WDdJa2hzQ3BEOTBEMy1mekxySXhCZlAwMkN3dGZUZGh4cmZyNHZkQS1tMTZjVnhMLUo5SmZkMHVxUUVOQ19QOWRVN1BWMTM5LWNqallrNDBFTXlMN29aaVRndllLMVV6MDhOWFF3YWxOZ2lGN2oyb3IwZGFtcDlKTGtVMTBGdz0 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/code/api/users_route.py", line 103, in validate_account
    name, email, pw_hash = decrypt_token('register', token)
  File "/code/api/helpers.py", line 145, in decrypt_token
    ciphertext = base64.urlsafe_b64decode(token.encode())
  File "/usr/local/lib/python3.5/base64.py", line 135, in urlsafe_b64decode
    return b64decode(s)
  File "/usr/local/lib/python3.5/base64.py", line 90, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

```

**Comment by Brutus5000** [comment]
This is a known issue. The generated tokens often end with `=` for padding. Some mail agents create an URL automatically but exclude the trailing `=`. The only solution I see is using HTML emails.

**Comment by micheljung** [comment]
Duplicate of #150
