### ISSUE TITLE
OAuth: ValueError: Scopes must be set on post auth.

### ISSUE THREAD

**Issue by IDragonfire** [FAForever/api#51]
OAuth catch if scope parameter is missing

`oauth/authorize?client_id=123&response_type=code`

![image](https://cloud.githubusercontent.com/assets/1217999/15328184/4cc9012c-1c54-11e6-842b-62fc15bc2ec2.png)

scope is optional:
https://tools.ietf.org/html/rfc6749#section-4.1.1

```
builtins.ValueError
ValueError: Scopes must be set on post auth.

Traceback (most recent call last)
This is the Copy/Paste friendly version of the traceback. You can also paste this traceback into a gist:  create paste
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/api/api/auth.py", line 37, in decorated_function
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flask_oauthlib/provider/oauth2.py", line 420, in decorated
    return self.confirm_authorization_request()
  File "/usr/local/lib/python3.5/dist-packages/flask_oauthlib/provider/oauth2.py", line 441, in confirm_authorization_request
    uri, http_method, body, headers, scopes, credentials)
  File "/usr/local/lib/python3.5/dist-packages/oauthlib/oauth2/rfc6749/endpoints/base.py", line 64, in wrapper
    return f(endpoint, uri, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/oauthlib/oauth2/rfc6749/endpoints/authorization.py", line 103, in create_authorization_response
    request, self.default_token_type)
  File "/usr/local/lib/python3.5/dist-packages/oauthlib/oauth2/rfc6749/grant_types/authorization_code.py", line 187, in create_authorization_response
    raise ValueError('Scopes must be set on post auth.')
ValueError: Scopes must be set on post auth.
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.
```

**Comment by micheljung** [comment]
Fixed in 607483c
