### ISSUE TITLE
OAuth: Cannot request token

### ISSUE THREAD

**Issue by IDragonfire** [FAForever/api#52]
https://tools.ietf.org/html/rfc6749#section-4.2.1

`/oauth/authorize?client_id=123&response_type=token`

```
builtins.AttributeError
AttributeError: 'NoneType' object has no attribute 'id'

Traceback (most recent call last)
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
raise value
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
raise value
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/vagrant/api/api/auth.py", line 37, in decorated_function
return function(*args, **kwargs)
File "/usr/local/lib/python3.5/dist-packages/flask_oauthlib/provider/oauth2.py", line 420, in decorated
return self.confirm_authorization_request()
File "/usr/local/lib/python3.5/dist-packages/flask_oauthlib/provider/oauth2.py", line 441, in confirm_authorization_request
uri, http_method, body, headers, scopes, credentials)
File "/usr/local/lib/python3.5/dist-packages/oauthlib/oauth2/rfc6749/endpoints/base.py", line 64, in wrapper
return f(endpoint, uri, *args, **kwargs)
File "/usr/local/lib/python3.5/dist-packages/oauthlib/oauth2/rfc6749/endpoints/authorization.py", line 103, in create_authorization_response
request, self.default_token_type)
File "/usr/local/lib/python3.5/dist-packages/oauthlib/oauth2/rfc6749/grant_types/implicit.py", line 161, in create_authorization_response
return self.create_token_response(request, token_handler)
File "/usr/local/lib/python3.5/dist-packages/oauthlib/oauth2/rfc6749/grant_types/implicit.py", line 231, in create_token_response
token = token_handler.create_token(request, refresh_token=False)
File "/usr/local/lib/python3.5/dist-packages/oauthlib/oauth2/rfc6749/tokens.py", line 280, in create_token
self.request_validator.save_bearer_token(token, request)
File "/usr/local/lib/python3.5/dist-packages/flask_oauthlib/provider/oauth2.py", line 728, in save_bearer_token
self._tokensetter(token, request, *args, **kwargs)
File "/vagrant/api/api/oauth_handlers.py", line 26, in set_token
OAuthToken.delete(request.client.client_id, request.user.id)
AttributeError: 'NoneType' object has no attribute 'id'
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.
```

![image](https://cloud.githubusercontent.com/assets/1217999/15329829/6f84821c-1c5a-11e6-872a-a3a01c96aef1.png)

**Comment by micheljung** [comment]
I see this as a duplicate of #51

**Comment by IDragonfire** [comment]
Why ... flask api source code:

![image](https://cloud.githubusercontent.com/assets/1217999/15340361/53e6d062-1c89-11e6-9db3-81494031fbb4.png)
