### ISSUE TITLE
Packet sequence number wrong - got 102 expected 1

### ISSUE THREAD

**Issue by micheljung** [FAForever/api#63]
```
 [2016-06-13 18:34:42,794] ERROR in app: Exception on /jwt/events/recordMultiple [POST]
 pymysql.err.InternalError: Packet sequence number wrong - got 2 expected 1
     (packet_number, self._next_seq_id))
   File "/usr/local/lib/python3.5/site-packages/pymysql/connections.py", line 968, in _read_packet
     auth_packet = self._read_packet()
   File "/usr/local/lib/python3.5/site-packages/pymysql/connections.py", line 1114, in _request_authentication
     self._request_authentication()
   File "/usr/local/lib/python3.5/site-packages/pymysql/connections.py", line 906, in connect
     self.connect()
   File "/usr/local/lib/python3.5/site-packages/pymysql/connections.py", line 863, in ping
     connection.ping()
   File "/code/db/faf/db/__init__.py", line 19, in get_cursor
     return self.cursor()
   File "/usr/local/lib/python3.5/site-packages/pymysql/connections.py", line 816, in __enter__
     with db.connection:
   File "/code/api/jwt_user.py", line 12, in get
     service_account = JwtUser.get(payload['iss'])
   File "/code/api/auth.py", line 47, in jwt_auth
     return self.view_functions[rule.endpoint](**req.view_args)
   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
     rv = self.dispatch_request()
   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
     raise value
   File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
     reraise(exc_type, exc_value, tb)
   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
     rv = self.handle_user_exception(e)
   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
     response = self.full_dispatch_request()
   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
 Traceback (most recent call last):

 During handling of the above exception, another exception occurred:

 pymysql.err.InternalError: Packet sequence number wrong - got 1 expected 2
     (packet_number, self._next_seq_id))
   File "/usr/local/lib/python3.5/site-packages/pymysql/connections.py", line 968, in _read_packet
     pkt = self._read_packet()
   File "/usr/local/lib/python3.5/site-packages/pymysql/connections.py", line 746, in _read_ok_packet
     return self._read_ok_packet()
   File "/usr/local/lib/python3.5/site-packages/pymysql/connections.py", line 860, in ping
```

The internet says this happens when you use pymysql in a wrong way, especially in a multithreaded environment.

This is one of the reasons the API returns 500 when storing events and achievements.

**Comment by micheljung** [comment]
Sheeo removed the use of ThreadPoolExecutor, API is single threaded again

**Comment by ghost** [comment]
What is pymysql version?

**Comment by Brutus5000** [comment]
https://github.com/FAForever/api/blob/develop/requirements.txt
